# Site wide configuration
title: "Matematične aktivnosti"
description: "Za osnovnošolce in vse, ki jih zanima matematika" # you can place here a subtitle
logo: # 120x120 px default image used for Twitter summary card
locale: sl
url: https://ul-fmf.github.io/matematicne-aktivnosti/
encoding: UTF-8

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .git
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - originali
