# Site wide configuration
title: "MatematiÄne aktivnosti"
description: # you can place here a subtitle
logo: # 120x120 px default image used for Twitter summary card
locale: sl
theme: jekyll-theme-architect